repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.51.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shfmt
      - id: shellcheck
 - repo: local
    hooks:
      - id: cfg-scripts
        name: Configure Scripts
        entry: pls cfg:scripts
        files: ^.*\.sh$
        pass_filenames: false
        language: system

      - id: hado-lint
        name: Lint Dockerfiles
        entry: pls lint:docker
        files: ^.*Dockerfile$
        pass_filenames: false
        language: system

      - id: ansible-lint
        name: Lints Ansible files
        entry: pls lint:ansible
        files: ^.*/playbooks/.*\.(yml)$
        pass_filenames: false
        language: system

      - id: yaml-fmt
        name: Format YAML with prettier
        entry: pls fmt:yaml
        files: ^.*\.(yaml|yml)$
        pass_filenames: false
        language: system

      - id: md-fmt
        name: Format Markdown with prettier
        entry: pls fmt:md
        files: ^.*\.(MD|md)$
        pass_filenames: false
        language: system

      - id: nixpkgs-fmt
        name: Format NIX files
        entry: pls fmt:nix
        files: ^.*\.nix$
        language: system
        pass_filenames: false