#cloud-config
users:
  - name: github-runner
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    shell: /usr/bin/bash
    lock_passwd: true
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDN6Ds6FNEhdnGeTRl7ppcefvrY9+xntFr32qHpcLA10/p2uhjXD/S8TvJmnDDf5nmbIW4YWRMku29rQ/2K6UwGXQvjzbI4ylHD1IxQjUZMP8hy2k6Eybro67/lybGTTVxggrTS1cUfSVnW63ALWX3Nb4DJH0UNrz7/ar8lzneDyS2pjUYdbXJHTJWyI/6qbr+MW9DrFBIWXe1tMqT8DimLnLJ2QnMq1cI5CSuxYpum/cCfLxv/zBnuzTjB6z0b1sx4Tp9LBzsun+beSv37y/DnDLIgzyuJQVqM5UibAW5NaNmYimT93UrdFeuB0GgYpcvt3q1EXUmPpuAhszjPrXDveRGZ1F/KsFgxYGohHChIy75DAH1dgb3qAeNiDmL4o+XYooaLQYnRBkKg2MeXghsPD0KNFyJwfE+bNDh2lE4aYXSnx5lPwwZrhbv0TE103yIC04IWQDuETUYXbjtMTG3+6ywldcPcPvymJw6vtOTjydzrjXbmopW6WOKtM6FlqBV845Dbp2T+j9nLK3x6qyozS2nAdDutd2wvhev2BTjBdxoKzdjrbsbdgDQAQqum9vqV0zmZz5+JBlnFCicj5+jwk/mfXVtlbYhQdoAydGWu/+Y1rnHxmpkZbNCC6ZIyccsNQdoQzZfO4XMo0hYUuD7jC3x8glTCgzzwzpiSUbw6ww== kirinnee@DESKTOP-1U7SGHF
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCj5rWgKxgoit2E2oyzL/hhfWKWQH+mQ7CzHCqxasbwp4539zWUgZIu8ig3wxVNrLLCvmXtxqa3MuohMUUA9Owodgl4lEWqbpNER1OFpqZYMmMVKgqYO/4WQdfmzBjxYkZwXo7E22j1C+StzAQH7ifxF7dBb5XSjzVJHK25toJAos7hqBT6CL9AM4zADtBmy8X3fvSOp/gx4R90QTMGMU+dFftp2bzhFh1+ykL5fnl4f1Zg/mhxGKxLpCLRu9N39GG5oCWB2MiCctwGpciRRSLvC91dQ+n7AJsgAkD3h37TJq4ViNQb7cCws4iy04ZPs7IBKZKJ8hMS4yBfBXZljbb2Hz5h1MQbh6nP9pAzpkKTCJ02ix+Kn5VVDAS/OKUR31g4vLU/+e/hqNs2rITg46BEhmOOH2/ya4oAF7QSS+4H5xyiTicejYzm2EtWs5nL+nUDrSGDaphFDIeXzb90auB2v7/ljcnxxKTUGLhhnN/FnVHbzu3PRhSZEAePrmt1OCGxT3zXMdFXGq5DUZ8e7CjAAeT4er8LgS8Q0lIslFDOwryPgcalxT/z/tcC5aCmg3yrHRJ4N1zSa2/2dPRDaHq1iNcX9NsCmObaMTRGadtzG6VQ87NaIosCCJeVUMMqcVeIuYZ+hQueK8eh3TR3AWi8LMeQ2KOdnGdfkYPxoGEi4Q== kirin@DESKTOP-1U7SGHF

package_update: true

apt:
  sources:
    docker.list:
      source: deb [arch=arm64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io

write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1

groups:
  - docker

system_info:
  default_user:
    groups: [docker]

runcmd:
  # install multi-user nix
  - sudo -u github-runner bash -c '{ curl -L "https://nixos.org/nix/install"; printf '%s\n%s\n%s\n%s\n%s\n' "y" "y" "y" "y" "y"; } | sh -s -- --daemon'
  # setup nix configurations
  - echo "keep-derivations = true" >> /etc/nix/nix.conf
  - echo "keep-outputs = true" >> /etc/nix/nix.conf

  # install github runner per user
  - sudo -u github-runner bash -c 'curl -L https://raw.githubusercontent.com/kirinnee/github-runner-setup/main/install-github-runner.sh | sh -s -- <hello> <url> <token> arm64'
